# Generated by Django 5.0.2 on 2024-02-17 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('is_role_good', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alive', models.BooleanField(default=True)),
                ('player_character', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wolfs_game.character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_next_round_active', models.BooleanField(default=True)),
                ('all_players', models.ManyToManyField(blank=True, default=None, related_name='all_games', to='wolfs_game.player')),
                ('good_players', models.ManyToManyField(blank=True, default=None, related_name='good_games', to='wolfs_game.player')),
                ('healer_vote', models.ManyToManyField(blank=True, default=None, related_name='healer_vote_games', to='wolfs_game.player')),
                ('wolf_votes', models.ManyToManyField(blank=True, default=None, related_name='wolf_votes_games', to='wolfs_game.player')),
                ('wolfs', models.ManyToManyField(blank=True, default=None, related_name='wolf_games', to='wolfs_game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='administered_rooms', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='joined_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='wolfs_game.room'),
        ),
    ]
